### ISSUE TITLE
Add customizable accent coloration

### ISSUE THREAD

**Issue by lal65** [PSU-OOE/components#245]
There are three general kinds of accents:

1.  Decorative accents - able to be used when the accent color is not the only design aspect that conveys semantic meaning in context. An obvious example of a decorative accent is the heading overlines that appear on H1 and H2 elements. The size of the heading element also conveys visual meaning of what level the heading is.
2.  Semantic accents - must be used when the accent color is the only design aspect that conveys a semantic meaning in context, or the WCAG dictates that color contrast requirements must be met in a particular context. An obvious example of a semantic accent color is a focus outline.
3.  Focus indication rings

In the design system, accent colors should come in four varieties.

1.  Decorative accent colors (default)
2.  Decorative accent colors (applied when on dark backgrounds)
3.  Semantic accent colors (default)
4.  Semantic accent colors (applied when on dark backgrounds)
5.  Focus indication rings (default)
6.  Focus indication rings (applied when on dark backgrounds)

The light / dark variations of both accent types should auto-switch based on context. Each color should be defined by a custom property such that the exposed front-end API meets:

```
/* Applied by default in semantic contexts. */
--accent-color--dark: <color>;

/* Applied in semantic contexts within a dark container. */
--accent-color--light: <color>;

/* Applied by default in non-semantic contexts. */
--accent-color-semantic--dark: <color>;

/* Applied in non-semantic contexts within a dark container. */
--accent-color-semantic--light: <color>;

/* Applied to focus rings in default and light contexts. */
--focus-indicator-color--dark: <color>;

/* Applied to focus rings in dark contexts. */
--focus-indicator-color--light: <color>;
```

_Note - there may very well be no current uses of `--accent-color-semantic`, but that's okay.  There will be eventually._

Apply non-semantic color properties to...

*   blockquote quotes
*   heading overlines
*   horizontal menu lines
*   drop panel left color

Apply focus indicator color properties to...

*   Accordions focus-visible outline
*   Base:
    *   styles.scss: focus-visible outline
*   Basic-tile: focus-visible outline
*   Card: focus-visible outline
*   Compact-menu: focus-visible outline
*   Compact-search: focus-visible outline
*   CTA:
    *   \_cta-block.scss: focus-visible outline
*   Event-link: focus-visible outline
*   Horizontal-menu: focus-visible outlines
*   Input-checkbox: focus-visible outline
*   Input-common: focus-visible outline
*   Input-file: focus-visible outline
*   Input-radio: focus-visible outline
*   Input-range: focus-visible outline
*   Modal: focus-visible outline
*   Navigation-tile-image: focus-visible outline
*   Select: focus-visible outline
*   Spinner: focus-visible outline
*   Tabs:
    *   \_tabs-list.scss: focus-visible outline
    *   \_tabs.scss: focus-visible ::before
*   Text-area: focus-visible outline
*   Vertical-menu: focus-visible outline

**Comment by lal65** [comment]
First audit all of the things that it might apply to (outlines, overlines, etc.)

Interactive / Semantic color sky blue by default on wcstudent (probably).

**Comment by bnh10** [comment]
**Accordions: focus-visible outline**
Alert: N/A
Announcement: N/A
Auto-expansion: N/A (No SCSS)
Background-container: N/A
Band: N/A
**Base:
    variables/_blockquote.scss: before/after on blockquote
    styles.scss: focus-visible outline**
**Basic-tile: focus-visible outline**
Bio-collection: N/A
Bio: N/A
Breadcrumbs: N/A
Callout: N/A
**Card: focus-visible outline**
Cards-list: N/A
**Compact-menu: focus-visible outline
Compact-search: focus-visible outline**
Credential: N/A
CTA-tracking: N/A (No SCSS)
**CTA:
    _cta-block.scss: focus-visible outline**
Details: N/A
Divider: N/A
Drop-button: N/A
**Event-link: focus-visible outline**
Expandable-section: N/A
Fieldset: N/A
Flex-wrap-listener: N/A (No SCSS)
Form: N/A
Grid: N/A
GTM: N/A (No SCSS)
Header: N/A
**Heading: background-color on overlines**
Highlighted-text: N/A
**Horizontal-menu: focus-visible outlines, background-color on ::before and ::after**
Icon-list: N/A
Infographic: N/A
**Input-checkbox: focus-visible outline**
Input-color: N/A
**Input-common: focus-visible outline**
Input-date: N/A
Input-email: N/A (No SCSS)
**Input-file: focus-visible outline**
Input-number: N/A (No SCSS)
Input-password: N/A (No SCSS)
**Input-radio: focus-visible outline
Input-range: focus-visible outline**
Input-search: N/A (No SCSS)
Input-tel: N/A (No SCSS)
Input-text: N/A (No SCSS)
Input-time: N/A
Input-url: N/A (No SCSS)
Intro-form: N/A
Label: N/A
Legend: N/A
**Modal: focus-visible outline**
More-menu: N/A
**Navigation-tile-image: focus-visible outline**
Navigation-tile: N/A
Overlay: N/A
Page-title-banner-image: N/A
Page-title-banner-plain: N/A
Page-title: N/A
Pager: N/A
Parallel-navigation-item: N/A
Parallel-navigation: N/A
Quote: N/A
Random-item: N/A (No SCSS)
Read-more: N/A
Section-view-tracking: N/A (No SCSS)
**Select: focus-visible outline**
Skip-link: N/A
Slide-toggle: N/A (No SCSS)
Smart-datetime: N/A
Social-icon: N/A
Social-icons: N/A
**Spinner: focus-visible outline**
Sprite: N/A
Sticky-panel: N/A
**Tabs:
    _tabs-list.scss: focus-visible outline
    _tabs.scss: focus-visible ::before
Text-area: focus-visible outline**
Upcoming-events: N/A
**Vertical-menu: focus-visible outline**

**Comment by lal65** [comment]
Correct me if I'm wrong, @mryand, but in each of those 4 components that are called out above, the accent coloration is not the only visual indicator of semantic value, is it?

**Comment by bnh10** [comment]
@mryand and @lal65 - If any of these are wrong or if I'm missing anything, please let me know!

Non-semantic color props:

base/variables/_blockquote.scss: blockquote quotes
drop-button: drop panel left color
heading: h1 and h2 ::before
horizontal menu: ::before and ::afters
vertical menu: border-left ::before for highlight

**Comment by mryand** [comment]
For the horizontal menu, I don’t know what the befores and afters all
represent. If one is the underline on the current item, that is semantic.
The left border color on the hover/open items is not semantic.

For the block quotes, I think they are semantic. Without the quote marks
it’s not visually apparent that it is a quote.

Everything else is not-semantic.

**Comment by lal65** [comment]
We can follow-up on this on your new Linux workstation tomorrow, @bnh10 :partying_face:.

![image](https://github.com/user-attachments/assets/bc49de2c-00bb-4fb4-9fbc-1b25f673fd75)
