### ISSUE TITLE
Add customizable color options to horizontal menu

### ISSUE THREAD

**Issue by lal65** [PSU-OOE/components#252]
This is a bit tricky!  Sometimes we want place this menu within a larger context that might have a gradient applied across it, so we can't explicitly set *all* coloration within the component itself.

I think this might be a problem best solved a bit indirectly by the use of some custom CSS properties, rather than coming up with new twig-based flavors of things.

```
--horizontal-menu-link-active-background-color: <color>
--horizontal-menu-link-active-foreground-color: <color>
```

whose fallback values are `--pa-link` and `--text-color`

https://developers.outreach.psu.edu/horizontal-menu-colors/?p=viewall-organisms-horizontal-menu

**Comment by mryand** [comment]
One issue I'm seeing is that we need the keyboard focus indication to be `pa-link` on the yellow background to ensure accessible contrast.

**Comment by mryand** [comment]
We may need to also pass in the focus color as well as the "current" underline color (since that also needs sufficient contrast with backgrounds).

**Comment by lal65** [comment]
@mryand - this seems to be a spot where we could use the concept of the "semantic accent color" that Brianne's currently working on, yes?
