### ISSUE TITLE
Add minimum widths to various things

### ISSUE THREAD

**Issue by lal65** [PSU-OOE/components#289]
These components need minimum widths put on their outer-most DOM element.

- [x] Accordion Item: 15rem
- [x] Basic Tile: 12rem
- [x] Card: 15rem
- [x] Credential: 12rem
- [x] CTA Group: 10rem
- [x] Infographic: 23rem
- [x] Intro Form: 20rem
- [x] Overlay: 20rem
- [x] Parallel Navigation Item: 10rem
- [x] Skip Link: 4rem
- [x] Social Icon: 4.4rem
- [x] Spinner: 2rem

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
